version: "3.8"

services:
  runner:
    image: r3dchilli/gh-runner:latest
    restart: always
    environment:
      - REPO=R3DChiLLi/github-actions-runner-dockerized
      - TOKEN=                     # ← pass your PAT with an env-file or export
      - DISABLE_RUNNER_UPDATE=true
      - RUNNER_DISABLE_UPDATE=true
      - RUNNER_NAME=runner-{{.Task.Slot}}  # unique name per replica
    deploy:
      mode: replicated
      replicas: 4
      resources:
        limits:
          cpus: "0.35"
          memory: 300M
        reservations:
          cpus: "0.25"
          memory: 128M
    volumes:
      - runner_data:/home/docker/actions-runner

volumes:
  runner_data:
    name: runner_data-{{.Task.Slot}}       # ← one volume per replica
    driver: local
